### ISSUE TITLE
git-changebar fails to compile with libgit2-1.4.0

### ISSUE THREAD

**Issue by cjmayo** [geany/geany-plugins#1164]
```
gcb-plugin.c: In function ‘gcb_git_buf_grow’:
gcb-plugin.c:219:12: error: ‘git_buf’ has no member named ‘asize’; did you mean ‘size’?
  219 |   if (buf->asize == 0) {
      |            ^~~~~
      |            size
gcb-plugin.c: In function ‘buf_zero’:
gcb-plugin.c:237:10: error: ‘git_buf’ has no member named ‘asize’; did you mean ‘size’?
  237 |     buf->asize = 0;
      |          ^~~~~
      |          size
```

geany-plugins 1.38.0

**Comment by dvzrv** [comment]
We are also seeing this on Arch Linux and it is blocking our upgrade to libgit2 1.4.1. A fix for this would be much appreciated! :)

**Comment by elextr** [comment]
It is going to be (literally) years before Debian stable or Ubuntu LTS get to libgit1.4.1 so I presume that the plugin maintainer will still want it to build against earlier libgit versions.  

So when somebody makes a PR the code using new API should be `#if`ed based on what version is being built against and I expect configure should enable the right version.

**Comment by eht16** [comment]
@dvzrv's approach is good. I added the necessary `ifdef`s in #1165.

However, as said in the PR, in the long term more code refactoring will be necessary as the whole `git_buf` object is now meant to be readonly and we use APIs to modify it but those APIs are already deprecated.
