### PR TITLE
Refactor panel option setting code into a seperate function

### PR DESCRIPTION
**Pull request by eht16**
This fixes a 'false positive' from cppcheck:
dconfig.c:351: error: va_list 'ap' was opened but not closed by va_end().

Probably cppcheck got confused by the nested while, switch and
break statements.

See also the output of last night's Debian Unstable build using cppcheck 1.74:
http://pastebin.geany.org/isOyz/

### CODE REVIEW

**Comment by eht16** [comment]
Don't merge this.
Scope is affected in a similar way and this is a bug in cppcheck which got already fixed:
http://trac.cppcheck.net/ticket/7533

So we just need to wait for a new cppcheck version.
