### ISSUE TITLE
git-changebar: Fails to build with libgit2/libgit2 1.5.0

### ISSUE THREAD

**Issue by madpilot78** [geany/geany-plugins#1211]
Hi,

Recent libgit has removed asize from the `struct git_buf`, which leads to this build failure:

```
gcb-plugin.c:219:12: error: no member named 'asize' in 'git_buf'; did you mean 'size'?
  if (buf->asize == 0) {
           ^~~~~
           size
/usr/local/include/git2/buffer.h:51:9: note: 'size' declared here
        size_t size;
               ^
gcb-plugin.c:237:10: error: no member named 'asize' in 'git_buf'; did you mean 'size'?
    buf->asize = 0;
         ^~~~~
         size
/usr/local/include/git2/buffer.h:51:9: note: 'size' declared here
        size_t size;
               ^
```

Not sure how this should be fixed, since the code is explicitly using asize.

I have no knowledge of libgit API, so I'm not sure I can create a patch. I'm testing a very brutal approach, to just remove al calls to `git_buf_grow()` and it's wrapper, but I'm not sure what the consequences could be,

**Comment by elextr** [comment]
Are you sure you have the latest from Git?  The line numbers don't seem to line up.

**Comment by madpilot78** [comment]
@elextr OH, sorry, I'm using 1.38 and did not notice head already contains a fix.

I'm the maintainer of hte FreeBSD geany ports, and was trying to build a failure in the ports tree.

I'll import the required patches to fix it there.

Thanks for pointing this out.
