### PR TITLE
git-changebar: Add support for libgit2 1.4 

### LINKED ISSUE #1164: git-changebar fails to compile with libgit2-1.4.0
```
gcb-plugin.c: In function ‘gcb_git_buf_grow’:
gcb-plugin.c:219:12: error: ‘git_buf’ has no member named ‘asize’; did you mean ‘size’?
  219 |   if (buf->asize == 0) {
      |            ^~~~~
      |            size
gcb-plugin.c: In function ‘buf_zero’:
gcb-plugin.c:237:10: error: ‘git_buf’ has no member named ‘asize’; did you mean ‘size’?
  237 |     buf->asize = 0;
      |          ^~~~~
      |          size
```

geany-plugins 1.38.0

### PR DESCRIPTION
**Pull request by cwendling**
This should fix #1164 , and replaces #1165.

BEWARE: I did NOT test this with libgit2 1.4, that I don't have yet.  I might go to the trouble of building it and all, but for now this is a theoretical PR, but if libgit2 1.4 users can verify it it'd be great.

### CODE REVIEW

**Comment by cwendling** [comment]
Sorry, opened withe the wrong account. See #1178.
